### ISSUE TITLE
ModuleNotFoundError: No module named 'scrappy'

### ISSUE THREAD

**Issue by HLHsieh** [yaozhong/methBERT#3]
Hi there,

I followed the instructions and tried to test `python3 train_biRNN.py`, but I received the following error message:

```
Traceback (most recent call last):                                                                                                                             
  File "train_biRNN.py", line 7, in <module>                                                                                                                   
    from dataProcess.data_loading import *
  File "/hsinlun/bin/methBERT/methBERT/dataProcess/data_loading.py", line 3, in <module>
    from .ref_util import get_fast5s, sim_seq_singal, pdist
  File "hsinlun/bin/methBERT/methBERT/dataProcess/ref_util.py", line 10, in <module>
    import scrappy
ModuleNotFoundError: No module named 'scrappy'
```

I would appreciate any suggestions you may have for resolving this issue.

Thank you for your time and assistance.

Best regards,
Hsin

**Comment by yaozhong** [comment]
HI, Hsin

According to the message, your current environment requires scrappy package install

https://github.com/nanoporetech/scrappie


Or you can use our provided docker environment as in https://methbert.readthedocs.io/en/latest/installation.html

**Comment by larryfoo** [comment]
Hi, i have install scrappy package. But it doesn't work. Should I add it to pip PATH?

**Comment by yaozhong** [comment]
HI, Larry

Can you show the detailed error information?

**Comment by larryfoo** [comment]
Hi, yaozhong

I finally solve the problem. At first, I installed the scrappy, but it doesn't work. Then I find the python version of scrappy that can solve the problem. 

Thank you for your time and assistance.

Best regards,
Larry Foo
