### ISSUE TITLE
UnboundLocalError: local variable 'net' referenced before assignment

### ISSUE THREAD

**Issue by larryfoo** [yaozhong/methBERT#4]
Hi, yaozheng

Thanks to your help in last time. Recently, I'm trying to use detect.py and meet such a problem:
``` shell
python /home/yqfu/software/methBERT/methBERT/detect.py --model M_dam_gAtc --model_dir /home/yqfu/software/methBERT/trained_model/Stoiber/random_split_balanced/R9_6mA/M_dam_gAtc/BERT_plus_W21_E50_stoiber_ecoli-M_dam_gAtc_basic_lr-1e-4-128.pth  \
>  --fast5_fold /home/data/yqfu/nanopore/single_fast5/C_fast5 --num_worker 12 \
> --motif A --ref_genome /home/data/yqfu/nanopore/ref_genome/ref.fa  --output_file /home/data/yqfu/nanopore/methBERT
[+] Detecting methylation A-motif with for 0-th position [A] for nanopore fast5 data ...
/home/data/yqfu/nanopore/single_fast5/C_fast5
 |- Loading single fold data with label-[1] ...
/home/yqfu/miniconda3/lib/python3.9/site-packages/torch/cuda/__init__.py:141: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0
* Loading trained model ...
Traceback (most recent call last):
  File "/home/yqfu/software/methBERT/methBERT/detect.py", line 166, in <module>
    detection_run(data_gen, device, args.model, args.model_dir, args.evalMode, False, args.ref_genome, args.output_file)
  File "/home/yqfu/software/methBERT/methBERT/detect.py", line 87, in detection_run
    net.to(device)
UnboundLocalError: local variable 'net' referenced before assignment
```
It seems like it has not assign 'net'

**Comment by yaozhong** [comment]
HI, 

Thanks for using.
According to your provided information, the model you are using is “--model M_dam_gAtc”.
In the current version, we only provide models of “ biRNN_basic/BERT/BERT_plus”.
(You can find it in the detect.py)

As “ M_dam_gAtc” is not the pre-provided model, this makes this error that NN model is not loaded properly.
Therefore, the consequent error happens when you intend to load the unloaded  model to GPU.

You can solve this through (1). Using provided models of “ biRNN_basic/BERT/BERT_plus” (e.g. —model biRNN_basic)
Or  (2) define your own model and revise the according parts in the code.
